FROM openjdk:8-jre-alpine
MAINTAINER Maciej Łotysz <maciej.lotysz@intive.com>
ADD target/backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
#https://medium.com/@cl4r1ty/docker-spring-boot-and-java-opts-ba381c818fa2#.bvcewql21
ENV JAVA_OPTS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
ENTRYPOINT exec java $JAVA_OPTS \
            -Djava.security.egd=file:/dev/./urandom \
            -jar /app.jar
