INSERT INTO category (ID, NAME ) SELECT ID, NAME FROM CSVREAD('classpath:data/categories.csv');
INSERT INTO user (ID, ADDITIONAL_INFO, EMAIL, NAME, PHONE_NUMBER) SELECT ID, ADDITIONAL_INFO, EMAIL, NAME, PHONE_NUMBER FROM CSVREAD('classpath:data/users.csv');
INSERT INTO offer (ID, BASE_DESCRIPTION, BASE_PRICE, DATE, EXTENDED_DESCRIPTION, EXTENDED_PRICE, EXTRA_DESCRIPTION, EXTRA_PRICE, TITLE, CATEGORY_ID, USER_ID) SELECT ID, BASE_DESCRIPTION, BASE_PRICE, DATE, EXTENDED_DESCRIPTION, EXTENDED_PRICE, EXTRA_DESCRIPTION, EXTRA_PRICE, TITLE, CATEGORY_ID, USER_ID FROM CSVREAD('classpath:data/offers.csv');

